### ISSUE TITLE
counter zählt falsch (zu viel)

### ISSUE THREAD

**Issue by artcrime** [BenAhrdt/ioBroker.bidirectional-counter#104]
Ich nutze den Adapter bidirektional-counter  seit einiger zeit um die Produktion meiner Minisolaranlage zu protokollieren.
Seit einigen Tagen werde völlig falsche Werte generiert, teils um Faktor 10 zu hoch. Es werden Werte angegeben welche mit meiner Anlage gar nicht möglich sind.
Ist es da in den letzten Versionen ggfls. zu einem Fehler gekommen? Ich nutze Version 2.1.0 des Adapters.

**Comment by BenAhrdt** [comment]
Es hat sich nichts funktionelles in den Versionen geändert.
Der Adapter zieht auch nur werte zusammen, die wirklich im DP Stehen, es wird nichts berechnet.
Ist es ein bleibendes Problem?
Wenn ja:
Leider habe ich aktuell keinen Debug-log eingebaut, der die Werte mit logt, die rein kommen.
Könntest Du Dir eventuell mal einen Trigger Bauen, der Änderungen in deinem ursprünglichen State mitloggt?
Denn, das ist der Wert, der geschrieben wird, wenn sich ein Wert ändert:

`const difference = Number(state.val) - this.activeStates[id].lastValue;`

also eigentlich nur Wert = Neu - Alt

Zur not müsste ich eine neue Version bauen mit Deb-Logs drin.

**Comment by BenAhrdt** [comment]
@artcrime ich Baue Dir gerade eine 2.1.3.
Dort wird bei Wertänderung im Debug mitgeloggt, was erkannt und geschrieben wurde.
Vielleicht könntest Du diese Version dann einmal installieren und einen Debuglog erzeugen.

**Comment by artcrime** [comment]
Seit ich den Adapter installiert habe scheint der Fehler nicht mehr aufzutreten. Bisher stimmen alle Daten mit den Ausgaben des Wechselrichters überein.
Evtl. hat die Installation des Adapters das Problem behoben? Vorher hatte ich bereits den Adapter neu gestartet und die Berechnung deaktiviert / aktiviert, beides ohne Erfolg.

**Comment by BenAhrdt** [comment]
@artcrime Keine Ahnung. Also ich habe bei dem Adapter nichts feststellen können.
Wenn es ja geht, dann schließe ich das issue.
